sudo: false
language: node_js
node_js:
    - '6'
install:
    - npm install
before_script:
    - npm run lint
script:
    - npm run build
deploy:
    skip_cleanup: true
    provider: surge
    project: ./public/
    domain: team3.surge.sh
