sudo: false
language: node_js
node_js:
    - '6'
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
install:
    - npm install
before_script:
    - npm run lint
after_success:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build'
deploy:
    skip_cleanup: true
    provider: surge
    project: ./public/
    domain: team3.surge.sh
services: mongodb
env:
  - TRAVIS=travis CXX=g++-4.8
